# --- 网站基础信息 ---
title: 枕松闲居
author: 梁贺
email: ""
description: >-
  在 AI、科研与职业选择中，记录自己的成长路径。

# --- 网站地址设置 ---
url: "https://lhe20603-oss.github.io"
baseurl: ""

# --- 核心系统设置 ---
markdown: kramdown
theme: minima

plugins:
  - jekyll-feed

# --- 排除不需要处理的文件 ---
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
